version: "3.2"
networks:
    netaxe-web:
        driver: bridge
        ipam:
            config:
                - subnet: 192.168.15.0/24
services:
    netaxe-web:
        # image: registry.cn-hangzhou.aliyuncs.com/netaxe/netaxe-web:1.0.4
        build:
            context: ../../web
        container_name: netaxe-web
        volumes:
            - ../../web/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8888:80"
        networks:
            - netaxe-web
