# Generated by Django 3.2.23 on 2026-03-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workflowexecution',
            name='state',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Published', 'Published'), ('Failed', 'Failed'), ('BackOff', 'BackOff'), ('Finish', 'Finish'), ('running', 'running'), ('verifying', 'verifying'), ('succeeded', 'succeeded'), ('partial', 'partial'), ('rolled_back', 'rolled_back'), ('cancelled', 'cancelled')], default='Draft', max_length=200, verbose_name='流程状态'),
        ),
        migrations.AlterField(
            model_name='workflowexecution',
            name='task',
            field=models.CharField(choices=[('变更', '变更'), ('DNAT', 'DNAT'), ('SNAT', 'SNAT'), ('安全策略', '安全策略'), ('QOS', 'QOS'), ('SLB负载均衡', 'SLB负载均衡'), ('一键封堵', '一键封堵'), ('地址对象', '地址对象'), ('服务对象', '服务对象'), ('一键切换', '一键切换'), ('巡检', '巡检')], default='', max_length=128, verbose_name='任务模块'),
        ),
    ]
