version: "3.7"

services:
    # 后端入口
    base-backend:
      image: registry.cn-hangzhou.aliyuncs.com/netaxe/base-backend:1.0
      build:
          context: .
          dockerfile: ./dockerfiles/backend_dockerfile
      command: sh start.sh web
      networks:
          - "netaxe-network"
      restart: always

    # nginx代理
    base-nginx:
      image: registry.cn-hangzhou.aliyuncs.com/netaxe/nginx:1.23.1
      volumes: # 数据卷挂载
        - ./backend-nginx.conf:/etc/nginx/nginx.conf
      networks:
        - "netaxe-network"
      ports:
        - "31101:80"

    # 前端
    base-web:
      image: registry.cn-hangzhou.aliyuncs.com/netaxe/base-web:1.0
      build:
        context: .
        dockerfile: ./dockerfiles/web_dockerfile
      ports:
        - "9904:80"
      networks:
        - "netaxe-network"
      restart: always

networks:
  netaxe-network:
    name: "netaxe-network"
