# Generated by Django 3.2.23 on 2026-03-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_analysis', '0002_analysisrun'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='analysisrun',
            name='network_ana_run_kin_574355_idx',
        ),
        migrations.RemoveIndex(
            model_name='analysisrun',
            name='network_ana_created_5d5ac3_idx',
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['run_kind', 'status'], name='network_ana_run_kin_1dc10f_idx'),
        ),
        migrations.AddIndex(
            model_name='analysisrun',
            index=models.Index(fields=['created_at'], name='network_ana_created_5aa234_idx'),
        ),
    ]
