# Generated by Django 3.2.23 on 2025-11-13 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCollectionPlans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='父采集方案名称')),
                ('vendor', models.CharField(choices=[('H3C', '华三'), ('Huawei', '华为'), ('Ruijie', '锐捷'), ('Hillstone', '山石'), ('Cisco', '思科'), ('Mellanox', 'Mellanox'), ('ZTE', '中兴'), ('centec', '盛科'), ('colasoft', '科来'), ('DELL', '戴尔'), ('F5', 'F5'), ('Maipu', '迈普'), ('Citrix', 'Citrix'), ('sangfor', '深信服'), ('inspur', '浪潮思科'), ('nsfocus', '绿盟'), ('nettap', '成都数维'), ('TJX', '腾捷兴')], max_length=30, verbose_name='厂商')),
                ('device_type', models.CharField(max_length=30, verbose_name='设备类型')),
                ('description', models.TextField(blank=True, null=True, verbose_name='描述')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '父采集方案',
                'verbose_name_plural': '父采集方案',
                'db_table': 'device_api_collection_plans',
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSubCollectionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='子采集方案名称')),
                ('collection_type', models.CharField(default='arp', max_length=20, verbose_name='采集类型')),
                ('description', models.TextField(blank=True, verbose_name='方案描述')),
                ('netmiko_enabled', models.BooleanField(default=True, verbose_name='启用Netmiko')),
                ('netmiko_method', models.CharField(blank=True, default='', help_text='要执行的采集方法名称', max_length=100, verbose_name='Netmiko方法名称')),
                ('netmiko_path', models.CharField(blank=True, default='', max_length=150, verbose_name='Netmiko路径')),
                ('netmiko_field_mappings', models.JSONField(blank=True, default=dict, verbose_name='Netmiko字段映射配置')),
                ('netmiko_processor_enabled', models.BooleanField(default=False, verbose_name='Netmiko是否启用数据处理')),
                ('netmiko_processor', models.TextField(blank=True, null=True, verbose_name='Netmiko数据处理代码')),
                ('netconf_enabled', models.BooleanField(default=False, verbose_name='启用NETCONF')),
                ('netconf_path', models.CharField(blank=True, default='', max_length=150, verbose_name='NETCONF路径')),
                ('netconf_field_mappings', models.JSONField(blank=True, default=dict, verbose_name='NETCONF字段映射配置')),
                ('netconf_processor_enabled', models.BooleanField(default=False, verbose_name='NETCONF是否启用数据处理')),
                ('netconf_processor', models.TextField(blank=True, null=True, verbose_name='NETCONF数据处理代码')),
                ('textfsm_template', models.CharField(blank=True, default='', max_length=100, verbose_name='TextFSM模板路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('summary_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collect_plans', to='device_api.devicecollectionplans', verbose_name='采集汇总方案')),
            ],
            options={
                'verbose_name': '子采集方案',
                'verbose_name_plural': '子采集方案',
                'db_table': 'device_api_sub_collection_plans',
                'ordering': ['name', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='NetconfXMLTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_method', models.CharField(choices=[('rpc', 'RPC'), ('get', 'GET'), ('get_config', 'GET_CONFIG')], max_length=20, verbose_name='采集方法')),
                ('xml_template', models.TextField(verbose_name='XML模板内容')),
                ('description', models.TextField(blank=True, null=True, verbose_name='模板描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('collection_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='xml_templates', to='device_api.devicesubcollectionplan', verbose_name='子采集方案')),
            ],
            options={
                'verbose_name': 'NETCONF XML模板',
                'verbose_name_plural': 'NETCONF XML模板',
                'db_table': 'device_api_netconf_xml_template',
                'ordering': ['collection_plan', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='netconfxmltemplate',
            index=models.Index(fields=['collection_plan'], name='device_api__collect_fd0966_idx'),
        ),
        migrations.AddIndex(
            model_name='netconfxmltemplate',
            index=models.Index(fields=['collect_method'], name='device_api__collect_a9d775_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='netconfxmltemplate',
            unique_together={('collection_plan', 'collect_method')},
        ),
        migrations.AddIndex(
            model_name='devicesubcollectionplan',
            index=models.Index(fields=['created_at'], name='device_api__created_0ce1da_idx'),
        ),
    ]
