# Generated by Django 3.2.23 on 2025-12-19 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlansToDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manage_ip', models.CharField(max_length=100, verbose_name='设备IP')),
                ('execute_node', models.CharField(blank=True, max_length=50, null=True, verbose_name='执行节点')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_plan', to='device_api.devicecollectionplans', verbose_name='关联方案')),
            ],
            options={
                'verbose_name': '采集方案关系表',
                'verbose_name_plural': '采集方案关系表',
                'db_table': 'device_api_plan2device',
                'ordering': ['manage_ip', 'created_at'],
            },
        ),
    ]
