# Generated by Django 3.2.23 on 2026-04-07 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('device_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceCollectionMatchRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10, verbose_name='规则名')),
                ('fields', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='匹配字段')),
                ('operator', models.CharField(blank=True, choices=[('__exact', '精确匹配'), ('__iexact', '不区分大小写的精确匹配'), ('__contains', '包含指定值'), ('__icontains', '不区分大小写包含指定值'), ('__startswith', '以指定值开头'), ('__endswith', '以指定值结尾'), ('__istartswith', '不区分大小写以指定值开头'), ('__iendswith', '不区分大小写以指定值结尾')], default='__exact', max_length=50, null=True, verbose_name='操作符')),
                ('value', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='匹配值')),
                ('legacy_match_rule_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='legacy匹配规则ID')),
            ],
            options={
                'verbose_name': '采集规则匹配项',
                'verbose_name_plural': '采集规则匹配项',
                'db_table': 'device_api_collection_match_rule',
            },
        ),
        migrations.CreateModel(
            name='DeviceCollectionRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='规则名')),
                ('operation', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='运算符')),
                ('module', models.CharField(choices=[('BASE', '基础平台'), ('SouthDriver', '南向驱动')], default='BASE', max_length=50, verbose_name='执行模块')),
                ('method', models.CharField(choices=[('NETCONF', 'NETCONF'), ('CLI', 'CLI'), ('REST_API', 'REST_API')], default='CLI', max_length=50, verbose_name='执行方法')),
                ('execute', models.TextField(blank=True, default='', verbose_name='执行内容')),
                ('plugin', models.CharField(default='', max_length=50, verbose_name='解析插件标识')),
                ('legacy_rule_id', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='legacy规则ID')),
            ],
            options={
                'verbose_name': '采集规则',
                'verbose_name_plural': '采集规则',
                'db_table': 'device_api_collection_rule',
            },
        ),
        migrations.CreateModel(
            name='DeviceDiscoveryState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_serial_num', models.CharField(max_length=200, unique=True, verbose_name='设备序列号')),
                ('manage_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='管理IP')),
                ('profile_code', models.CharField(blank=True, default='', max_length=64, verbose_name='画像编码')),
                ('capability_facts', models.JSONField(blank=True, default=dict, verbose_name='能力画像事实')),
                ('last_discovered_at', models.DateTimeField(blank=True, null=True, verbose_name='最近发现时间')),
                ('last_discovery_status', models.CharField(blank=True, default='pending', max_length=20, verbose_name='最近发现状态')),
                ('last_discovery_error', models.TextField(blank=True, default='', verbose_name='最近发现错误')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '设备发现状态',
                'verbose_name_plural': '设备发现状态',
                'db_table': 'device_api_device_discovery_state',
            },
        ),
        migrations.CreateModel(
            name='PlansToDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_serial_num', models.CharField(blank=True, default='', max_length=200, verbose_name='设备序列号')),
                ('manage_ip', models.CharField(max_length=100, verbose_name='设备IP')),
                ('profile_code', models.CharField(blank=True, default='', max_length=64, verbose_name='画像编码')),
                ('binding_source', models.CharField(choices=[('auto', '自动绑定'), ('manual', '手工绑定'), ('legacy_bridge', '旧链路桥接')], default='manual', max_length=20, verbose_name='绑定来源')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('use_local', models.BooleanField(default=True, help_text='默认True表示本地采集；设为False时使用南向驱动，由 execute_node 指定执行节点', verbose_name='使用本地采集')),
                ('execute_node', models.CharField(blank=True, default='', help_text='仅当 use_local=False 时生效，指定南向驱动节点地址或标识', max_length=200, verbose_name='南向驱动执行节点')),
                ('last_bound_at', models.DateTimeField(blank=True, null=True, verbose_name='最近绑定时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '采集方案关系表',
                'verbose_name_plural': '采集方案关系表',
                'db_table': 'device_api_plan2device',
                'ordering': ['manage_ip', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlatformProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='画像编码')),
                ('vendor_alias', models.CharField(max_length=30, verbose_name='厂商别名')),
                ('category', models.CharField(blank=True, default='', max_length=30, verbose_name='设备类型')),
                ('series_patterns', models.JSONField(blank=True, default=list, verbose_name='型号匹配规则')),
                ('os_family', models.CharField(blank=True, default='', max_length=64, verbose_name='操作系统族')),
                ('version_patterns', models.JSONField(blank=True, default=list, verbose_name='版本匹配规则')),
                ('preferred_methods', models.JSONField(blank=True, default=dict, verbose_name='优先采集协议')),
                ('fallback_methods', models.JSONField(blank=True, default=dict, verbose_name='回退采集协议')),
                ('supported_collection_types', models.JSONField(blank=True, default=list, verbose_name='支持的采集类型')),
                ('default_plan_name', models.CharField(blank=True, default='', max_length=100, verbose_name='默认方案名')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '平台画像',
                'verbose_name_plural': '平台画像',
                'db_table': 'device_api_platform_profile',
                'ordering': ['code'],
            },
        ),
        migrations.AddField(
            model_name='devicecollectionplans',
            name='collection_method',
            field=models.CharField(choices=[('netmiko', '仅 Netmiko'), ('netconf', '仅 NETCONF'), ('both', 'Netmiko + NETCONF')], default='netmiko', max_length=16, verbose_name='方案级采集方式'),
        ),
        migrations.AddField(
            model_name='devicecollectionplans',
            name='enabled_collection_types',
            field=models.JSONField(blank=True, default=list, verbose_name='启用的采集类型'),
        ),
        migrations.AddField(
            model_name='devicecollectionplans',
            name='generated_by_system',
            field=models.BooleanField(default=False, verbose_name='是否系统生成'),
        ),
        migrations.AddField(
            model_name='devicecollectionplans',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='是否默认方案'),
        ),
        migrations.AddField(
            model_name='devicecollectionplans',
            name='plan_kind',
            field=models.CharField(choices=[('template', '模板方案'), ('runtime', '运行时方案')], default='runtime', max_length=16, verbose_name='方案类型'),
        ),
        migrations.AddField(
            model_name='devicecollectionplans',
            name='profile_code',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='画像编码'),
        ),
        migrations.AddField(
            model_name='devicecollectionplans',
            name='recent_failed_device_count',
            field=models.PositiveIntegerField(default=0, verbose_name='最近失败设备数'),
        ),
        migrations.AddField(
            model_name='devicecollectionplans',
            name='recent_validation_status',
            field=models.CharField(blank=True, default='pending', max_length=32, verbose_name='最近验证状态'),
        ),
        migrations.AddField(
            model_name='devicecollectionplans',
            name='version',
            field=models.PositiveIntegerField(default=1, verbose_name='方案版本'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='latest_sample_result',
            field=models.TextField(blank=True, default='', verbose_name='最近样例结果'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='recent_failed_count',
            field=models.PositiveIntegerField(default=0, verbose_name='最近失败数'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='restconf_enabled',
            field=models.BooleanField(default=False, verbose_name='启用RESTCONF'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='restconf_endpoint',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='RESTCONF端点路径'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='restconf_field_mappings',
            field=models.JSONField(blank=True, default=dict, verbose_name='RESTCONF字段映射配置'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='restconf_method',
            field=models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=10, verbose_name='HTTP方法'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='restconf_path',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='RESTCONF路径'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='restconf_processor',
            field=models.TextField(blank=True, null=True, verbose_name='RESTCONF数据处理代码'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='restconf_processor_enabled',
            field=models.BooleanField(default=False, verbose_name='RESTCONF是否启用数据处理'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='snmp_enabled',
            field=models.BooleanField(default=False, verbose_name='启用SNMP'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='snmp_field_mappings',
            field=models.JSONField(blank=True, default=dict, verbose_name='SNMP字段映射配置'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='snmp_oids',
            field=models.JSONField(blank=True, default=list, help_text='OID列表，如: ["1.3.6.1.2.1.4.22.1.2", "1.3.6.1.2.1.4.22.1.3"]', verbose_name='SNMP OID列表'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='snmp_path',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='SNMP路径'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='snmp_processor',
            field=models.TextField(blank=True, null=True, verbose_name='SNMP数据处理代码'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='snmp_processor_enabled',
            field=models.BooleanField(default=False, verbose_name='SNMP是否启用数据处理'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='snmp_version',
            field=models.CharField(blank=True, choices=[('v1', 'v1'), ('v2c', 'v2c'), ('v3', 'v3')], default='v2c', max_length=10, verbose_name='SNMP版本'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='telemetry_data_format',
            field=models.CharField(blank=True, choices=[('gpb', 'GPB'), ('json', 'JSON')], default='json', max_length=20, verbose_name='数据格式'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='telemetry_enabled',
            field=models.BooleanField(default=False, verbose_name='启用Telemetry'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='telemetry_field_mappings',
            field=models.JSONField(blank=True, default=dict, verbose_name='Telemetry字段映射配置'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='telemetry_path',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Telemetry路径'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='telemetry_processor',
            field=models.TextField(blank=True, null=True, verbose_name='Telemetry数据处理代码'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='telemetry_processor_enabled',
            field=models.BooleanField(default=False, verbose_name='Telemetry是否启用数据处理'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='telemetry_sampling_interval',
            field=models.IntegerField(default=10, verbose_name='采样间隔（秒）'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='telemetry_subscription_path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Telemetry订阅路径'),
        ),
        migrations.AlterField(
            model_name='devicecollectionplans',
            name='vendor',
            field=models.CharField(max_length=30, verbose_name='厂商'),
        ),
        migrations.AlterField(
            model_name='devicesubcollectionplan',
            name='collection_type',
            field=models.CharField(default='arp', max_length=32, verbose_name='采集类型'),
        ),
        migrations.AlterField(
            model_name='devicesubcollectionplan',
            name='netmiko_enabled',
            field=models.BooleanField(default=False, verbose_name='启用Netmiko'),
        ),
        migrations.AlterField(
            model_name='netconfxmltemplate',
            name='collect_method',
            field=models.CharField(choices=[('get', 'GET'), ('get_config', 'GET_CONFIG')], max_length=20, verbose_name='采集方法'),
        ),
        migrations.AddIndex(
            model_name='devicecollectionplans',
            index=models.Index(fields=['profile_code', 'device_type'], name='device_api__profile_a0710c_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecollectionplans',
            index=models.Index(fields=['vendor', 'is_default'], name='device_api__vendor_7d5188_idx'),
        ),
        migrations.AddIndex(
            model_name='platformprofile',
            index=models.Index(fields=['vendor_alias', 'category'], name='device_api__vendor__6b4cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='platformprofile',
            index=models.Index(fields=['is_active'], name='device_api__is_acti_adbd99_idx'),
        ),
        migrations.AddField(
            model_name='planstodevice',
            name='plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_plan', to='device_api.devicecollectionplans', verbose_name='关联方案'),
        ),
        migrations.AddIndex(
            model_name='devicediscoverystate',
            index=models.Index(fields=['manage_ip'], name='device_api__manage__2562f3_idx'),
        ),
        migrations.AddIndex(
            model_name='devicediscoverystate',
            index=models.Index(fields=['profile_code', 'last_discovery_status'], name='device_api__profile_4b1d8e_idx'),
        ),
        migrations.AddIndex(
            model_name='devicecollectionrule',
            index=models.Index(fields=['id'], name='device_api__id_4eec09_idx'),
        ),
        migrations.AddField(
            model_name='devicecollectionmatchrule',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_rule', to='device_api.devicecollectionrule'),
        ),
        migrations.AddIndex(
            model_name='planstodevice',
            index=models.Index(fields=['device_serial_num', 'is_active'], name='device_api__device__e49f52_idx'),
        ),
        migrations.AddIndex(
            model_name='planstodevice',
            index=models.Index(fields=['manage_ip', 'profile_code'], name='device_api__manage__8c645e_idx'),
        ),
        migrations.AddConstraint(
            model_name='planstodevice',
            constraint=models.UniqueConstraint(fields=('device_serial_num', 'plan'), name='uniq_device_api_plan_binding'),
        ),
        migrations.AddIndex(
            model_name='devicecollectionmatchrule',
            index=models.Index(fields=['id'], name='device_api__id_cc0808_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicecollectionmatchrule',
            unique_together={('rule', 'name')},
        ),
    ]
