# Generated by Django 3.2.23 on 2025-12-18 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_api', '0002_planstodevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='planstodevice',
            name='execute_node',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='执行节点'),
        ),
    ]
