# Generated by Django 3.2.23 on 2026-01-09 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_api', '0002_planstodevice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='planstodevice',
            name='execute_node',
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='restconf_enabled',
            field=models.BooleanField(default=False, verbose_name='启用RESTCONF'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='restconf_endpoint',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='RESTCONF端点路径'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='restconf_field_mappings',
            field=models.JSONField(blank=True, default=dict, verbose_name='RESTCONF字段映射配置'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='restconf_method',
            field=models.CharField(blank=True, choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=10, verbose_name='HTTP方法'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='restconf_path',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='RESTCONF路径'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='restconf_processor',
            field=models.TextField(blank=True, null=True, verbose_name='RESTCONF数据处理代码'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='restconf_processor_enabled',
            field=models.BooleanField(default=False, verbose_name='RESTCONF是否启用数据处理'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='snmp_enabled',
            field=models.BooleanField(default=False, verbose_name='启用SNMP'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='snmp_field_mappings',
            field=models.JSONField(blank=True, default=dict, verbose_name='SNMP字段映射配置'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='snmp_oids',
            field=models.JSONField(blank=True, default=list, help_text='OID列表，如: ["1.3.6.1.2.1.4.22.1.2", "1.3.6.1.2.1.4.22.1.3"]', verbose_name='SNMP OID列表'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='snmp_path',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='SNMP路径'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='snmp_processor',
            field=models.TextField(blank=True, null=True, verbose_name='SNMP数据处理代码'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='snmp_processor_enabled',
            field=models.BooleanField(default=False, verbose_name='SNMP是否启用数据处理'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='snmp_version',
            field=models.CharField(blank=True, choices=[('v1', 'v1'), ('v2c', 'v2c'), ('v3', 'v3')], default='v2c', max_length=10, verbose_name='SNMP版本'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='telemetry_data_format',
            field=models.CharField(blank=True, choices=[('gpb', 'GPB'), ('json', 'JSON')], default='json', max_length=20, verbose_name='数据格式'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='telemetry_enabled',
            field=models.BooleanField(default=False, verbose_name='启用Telemetry'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='telemetry_field_mappings',
            field=models.JSONField(blank=True, default=dict, verbose_name='Telemetry字段映射配置'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='telemetry_path',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Telemetry路径'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='telemetry_processor',
            field=models.TextField(blank=True, null=True, verbose_name='Telemetry数据处理代码'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='telemetry_processor_enabled',
            field=models.BooleanField(default=False, verbose_name='Telemetry是否启用数据处理'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='telemetry_sampling_interval',
            field=models.IntegerField(default=10, verbose_name='采样间隔（秒）'),
        ),
        migrations.AddField(
            model_name='devicesubcollectionplan',
            name='telemetry_subscription_path',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='Telemetry订阅路径'),
        ),
    ]
