# Generated by Django 3.2.23 on 2026-03-23 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_api', '0010_devicediscoverystate_capability_facts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='netconfxmltemplate',
            name='collect_method',
            field=models.CharField(choices=[('get', 'GET'), ('get_config', 'GET_CONFIG')], max_length=20, verbose_name='采集方法'),
        ),
    ]
