# Generated by Django 3.2.19 on 2024-01-15 03:13

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='attribute',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.attribute', verbose_name='网络属性'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='expire',
            field=models.DateField(blank=True, null=True, verbose_name='维保日期'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='framework',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.framework', verbose_name='网络架构'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='idc_model',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.idcmodel', verbose_name='模块'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='rack',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.rack', verbose_name='机柜编号'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='role',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.role', verbose_name='设备角色'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='u_location_end',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)], verbose_name='机架位结束'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='u_location_start',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)], verbose_name='机架位起始'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='uptime',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='上线时间'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='zone',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.netzone', verbose_name='网络区域'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='attribute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attribute_asset', to='asset.attribute', verbose_name='网络属性'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='expire',
            field=models.DateField(blank=True, null=True, verbose_name='维保日期'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='framework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='framework_asset', to='asset.framework', verbose_name='网络架构'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='idc_model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idc_model_asset', to='asset.idcmodel', verbose_name='模块'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='rack',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rack_asset', to='asset.rack', verbose_name='机柜编号'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_asset', to='asset.role', verbose_name='设备角色'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='u_location_end',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)], verbose_name='机架位结束'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='u_location_start',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)], verbose_name='机架位起始'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='uptime',
            field=models.DateField(default=django.utils.timezone.now, null=True, verbose_name='上线时间'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='zone_asset', to='asset.netzone', verbose_name='网络区域'),
        ),
    ]
