# Generated by Django 3.2.23 on 2025-11-27 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='netconf_status',
            field=models.BooleanField(default=False, verbose_name='netconf状态'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='ssh_status',
            field=models.BooleanField(default=False, verbose_name='ssh状态'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='netconf_status',
            field=models.BooleanField(default=False, verbose_name='netconf状态'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='ssh_status',
            field=models.BooleanField(default=False, verbose_name='ssh状态'),
        ),
    ]
