# Generated by Django 3.2.19 on 2023-06-16 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminrecord',
            name='admin_record_cmds',
            field=models.TextField(default='', verbose_name='命令记录'),
        ),
        migrations.AddField(
            model_name='server',
            name='account',
            field=models.ManyToManyField(blank=True, to='asset.AssetAccount', verbose_name='管理账户'),
        ),
        migrations.AlterField(
            model_name='adminrecord',
            name='admin_server',
            field=models.CharField(max_length=200, verbose_name='登录主机'),
        ),
        migrations.DeleteModel(
            name='ServerAccount',
        ),
    ]
