# Generated by Django 3.2.19 on 2024-01-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20240115_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdevice',
            name='account',
            field=models.ManyToManyField(blank=True, to='asset.AssetAccount', verbose_name='管理账户'),
        ),
    ]
