# Generated by Django 3.2.23 on 2026-03-23 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20251219_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnetworkdevice',
            name='u_location_end',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(1)], verbose_name='机架位结束'),
        ),
        migrations.AlterField(
            model_name='historicalnetworkdevice',
            name='u_location_start',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(1)], verbose_name='机架位起始'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='u_location_end',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(1)], verbose_name='机架位结束'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='u_location_start',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(60), django.core.validators.MinValueValidator(1)], verbose_name='机架位起始'),
        ),
    ]
