# Generated by Django 3.2.19 on 2024-02-27 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20240115_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnetworkdevice',
            name='serial_num',
            field=models.CharField(db_index=True, max_length=200, verbose_name='序列号'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='account',
            field=models.ManyToManyField(blank=True, to='asset.AssetAccount', verbose_name='管理账户'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='serial_num',
            field=models.CharField(max_length=200, unique=True, verbose_name='序列号'),
        ),
    ]
