# Generated by Django 3.2.23 on 2025-12-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20251127_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='snmp_status',
            field=models.BooleanField(default=False, verbose_name='snmp状态'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='snmp_status',
            field=models.BooleanField(default=False, verbose_name='snmp状态'),
        ),
    ]
