# Generated by Django 3.2.19 on 2023-06-20 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20230616_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminrecord',
            name='admin_login_user',
            field=models.CharField(max_length=200, verbose_name='用户'),
        ),
    ]
