# Generated by Django 3.2.19 on 2024-02-29 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20240227_1002'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServerAccount',
        ),
    ]
