# Generated by Django 3.2.19 on 2024-03-04 07:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_delete_serveraccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='u_location',
        ),
        migrations.AddField(
            model_name='server',
            name='u_location_end',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)], verbose_name='机架位结束'),
        ),
        migrations.AddField(
            model_name='server',
            name='u_location_start',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(50), django.core.validators.MinValueValidator(1)], verbose_name='机架位起始'),
        ),
    ]
