# Generated by Django 3.2.19 on 2023-06-27 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_serveraccount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnetworkdevice',
            name='serial_num',
            field=models.CharField(max_length=200, verbose_name='序列号'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='serial_num',
            field=models.CharField(max_length=200, verbose_name='序列号'),
        ),
    ]
