# Generated by Django 3.2.19 on 2023-06-27 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20230627_1023'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='networkdevice',
            unique_together=set(),
        ),
    ]
