# Generated by Django 3.2.19 on 2024-07-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0005_auto_20240304_1555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servermodel',
            name='name',
            field=models.CharField(max_length=30, verbose_name='硬件型号'),
        ),
    ]
