# Generated by Django 3.2.19 on 2023-07-04 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_alter_networkdevice_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetaccount',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='管理账户'),
        ),
    ]
