# Generated by Django 3.2.19 on 2024-07-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_alter_networkdevice_account'),
        ('asset', '0006_alter_servermodel_name'),
    ]

    operations = [
    ]
