# Generated by Django 3.2.23 on 2024-10-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_merge_20240723_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnetworkdevice',
            name='uptime',
            field=models.DateField(blank=True, editable=False, null=True, verbose_name='上线时间'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='uptime',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='上线时间'),
        ),
    ]
