# Generated by Django 3.2.19 on 2023-07-10 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0007_alter_assetaccount_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerIpInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='标识名')),
                ('ipaddr', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='server_bind_ip', to='asset.server', verbose_name='关联服务器')),
            ],
            options={
                'verbose_name_plural': '服务器关联IP表',
                'db_table': 'server_ip',
            },
        ),
        migrations.AddIndex(
            model_name='serveripinfo',
            index=models.Index(fields=['name'], name='server_ip_name_a77c9d_idx'),
        ),
    ]
