# Generated by Django 3.2.23 on 2025-02-26 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_auto_20241027_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='snmp_community',
            field=models.CharField(default='-', max_length=50, verbose_name='SNMP community'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='snmp_port',
            field=models.IntegerField(default=161, verbose_name='snmp port'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='snmp_version',
            field=models.CharField(default='v2c', max_length=50, verbose_name='SNMP version'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='snmp_community',
            field=models.CharField(default='-', max_length=50, verbose_name='SNMP community'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='snmp_port',
            field=models.IntegerField(default=161, verbose_name='snmp port'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='snmp_version',
            field=models.CharField(default='v2c', max_length=50, verbose_name='SNMP version'),
        ),
        migrations.AlterField(
            model_name='historicalnetworkdevice',
            name='memo',
            field=models.TextField(blank=True, default='-', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='historicalnetworkdevice',
            name='name',
            field=models.CharField(default='-', max_length=100, verbose_name='资产名称'),
        ),
        migrations.AlterField(
            model_name='historicalnetworkdevice',
            name='patch_version',
            field=models.CharField(default='-', max_length=200, null=True, verbose_name='补丁版本'),
        ),
        migrations.AlterField(
            model_name='historicalnetworkdevice',
            name='soft_version',
            field=models.CharField(default='-', max_length=200, verbose_name='软件版本'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='memo',
            field=models.TextField(blank=True, default='-', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='name',
            field=models.CharField(default='-', max_length=100, verbose_name='资产名称'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='patch_version',
            field=models.CharField(default='-', max_length=200, null=True, verbose_name='补丁版本'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='soft_version',
            field=models.CharField(default='-', max_length=200, verbose_name='软件版本'),
        ),
    ]
