# Generated by Django 3.2.23 on 2025-04-02 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_auto_20241027_1438'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='is_monitor',
            field=models.BooleanField(default=False, verbose_name='是否监控'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='netconf_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.assetaccount', verbose_name='netconf纳管关联账户'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='netconf_enable',
            field=models.CharField(choices=[('0', '不纳管'), ('account', 'account')], default='0', max_length=50, verbose_name='NETCONF是否纳管'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='snmp_community',
            field=models.CharField(default='-', max_length=50, verbose_name='SNMP community'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='snmp_port',
            field=models.IntegerField(default=161, verbose_name='snmp port'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='snmp_version',
            field=models.CharField(default='v2c', max_length=50, verbose_name='SNMP version'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='ssh_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.assetaccount', verbose_name='ssh纳管关联账户'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='ssh_enable',
            field=models.CharField(choices=[('0', '不纳管'), ('account', 'account')], default='0', max_length=50, verbose_name='ssh是否纳管'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='is_monitor',
            field=models.BooleanField(default=False, verbose_name='是否监控'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='netconf_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releate_netconf', to='asset.assetaccount', verbose_name='netconf纳管关联账户'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='netconf_enable',
            field=models.CharField(choices=[('0', '不纳管'), ('account', 'account')], default='0', max_length=50, verbose_name='NETCONF是否纳管'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='snmp_community',
            field=models.CharField(default='-', max_length=50, verbose_name='SNMP community'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='snmp_port',
            field=models.IntegerField(default=161, verbose_name='snmp port'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='snmp_version',
            field=models.CharField(default='v2c', max_length=50, verbose_name='SNMP version'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='ssh_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releate_ssh', to='asset.assetaccount', verbose_name='ssh纳管关联账户'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='ssh_enable',
            field=models.CharField(choices=[('0', '不纳管'), ('account', 'account')], default='0', max_length=50, verbose_name='ssh是否纳管'),
        ),
        migrations.AlterField(
            model_name='historicalnetworkdevice',
            name='memo',
            field=models.TextField(blank=True, default='-', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='historicalnetworkdevice',
            name='name',
            field=models.CharField(default='-', max_length=100, verbose_name='资产名称'),
        ),
        migrations.AlterField(
            model_name='historicalnetworkdevice',
            name='patch_version',
            field=models.CharField(default='-', max_length=200, null=True, verbose_name='补丁版本'),
        ),
        migrations.AlterField(
            model_name='historicalnetworkdevice',
            name='soft_version',
            field=models.CharField(default='-', max_length=200, verbose_name='软件版本'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_asset', to='asset.category', verbose_name='设备类型'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='idc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idc_asset', to='asset.idc', verbose_name='所属机房'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='memo',
            field=models.TextField(blank=True, default='-', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_asset', to='asset.model', verbose_name='硬件型号'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='name',
            field=models.CharField(default='-', max_length=100, verbose_name='资产名称'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='patch_version',
            field=models.CharField(default='-', max_length=200, null=True, verbose_name='补丁版本'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='soft_version',
            field=models.CharField(default='-', max_length=200, verbose_name='软件版本'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_asset', to='asset.vendor', verbose_name='供应商'),
        ),
    ]
