# Generated by Django 3.2.19 on 2023-11-21 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_auto_20230710_1729'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkdevice',
            name='org',
        ),
    ]
