# Generated by Django 3.2.23 on 2025-02-27 08:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_auto_20250226_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='is_monitor',
            field=models.BooleanField(default=False, verbose_name='是否监控'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='netconf_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.assetaccount', verbose_name='netconf纳管关联账户'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='netconf_enable',
            field=models.CharField(choices=[('0', '不纳管'), ('1', '纳管'), ('account', 'account')], default='0', max_length=50, verbose_name='NETCONF是否纳管'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='netconf_password',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='登录密码'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='netconf_port',
            field=models.IntegerField(default=830, verbose_name='端口号'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='netconf_username',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='NETCONF登录用户名'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='ssh_account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='asset.assetaccount', verbose_name='ssh纳管关联账户'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='ssh_en_pwd',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='特权密码'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='ssh_enable',
            field=models.CharField(choices=[('0', '不纳管'), ('1', '纳管'), ('account', 'account')], default='0', max_length=50, verbose_name='ssh是否纳管'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='ssh_manage',
            field=models.CharField(choices=[('ssh', 'ssh'), ('telnet', 'telnet')], default='ssh', max_length=50, verbose_name='ssh纳管方式'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='ssh_password',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='登录密码'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='ssh_port',
            field=models.IntegerField(default=22, verbose_name='端口号'),
        ),
        migrations.AddField(
            model_name='historicalnetworkdevice',
            name='ssh_username',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='SSH登录用户名'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='is_monitor',
            field=models.BooleanField(default=False, verbose_name='是否监控'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='netconf_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releate_netconf', to='asset.assetaccount', verbose_name='netconf纳管关联账户'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='netconf_enable',
            field=models.CharField(choices=[('0', '不纳管'), ('1', '纳管'), ('account', 'account')], default='0', max_length=50, verbose_name='NETCONF是否纳管'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='netconf_password',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='登录密码'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='netconf_port',
            field=models.IntegerField(default=830, verbose_name='端口号'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='netconf_username',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='NETCONF登录用户名'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='ssh_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='releate_ssh', to='asset.assetaccount', verbose_name='ssh纳管关联账户'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='ssh_en_pwd',
            field=models.CharField(blank=True, default='', max_length=300, null=True, verbose_name='特权密码'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='ssh_enable',
            field=models.CharField(choices=[('0', '不纳管'), ('1', '纳管'), ('account', 'account')], default='0', max_length=50, verbose_name='ssh是否纳管'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='ssh_manage',
            field=models.CharField(choices=[('ssh', 'ssh'), ('telnet', 'telnet')], default='ssh', max_length=50, verbose_name='ssh纳管方式'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='ssh_password',
            field=models.CharField(blank=True, default='', max_length=200, null=True, verbose_name='登录密码'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='ssh_port',
            field=models.IntegerField(default=22, verbose_name='端口号'),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='ssh_username',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='SSH登录用户名'),
        ),
    ]
