# Generated by Django 3.2.19 on 2023-11-23 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0009_remove_networkdevice_org'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='networkdevice',
            name='asset_netwo_uptime_da13a6_idx',
        ),
        migrations.RemoveIndex(
            model_name='networkdevice',
            name='asset_netwo_expire_587d66_idx',
        ),
        migrations.RemoveField(
            model_name='historicalnetworkdevice',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='historicalnetworkdevice',
            name='expire',
        ),
        migrations.RemoveField(
            model_name='historicalnetworkdevice',
            name='framework',
        ),
        migrations.RemoveField(
            model_name='historicalnetworkdevice',
            name='idc_model',
        ),
        migrations.RemoveField(
            model_name='historicalnetworkdevice',
            name='rack',
        ),
        migrations.RemoveField(
            model_name='historicalnetworkdevice',
            name='role',
        ),
        migrations.RemoveField(
            model_name='historicalnetworkdevice',
            name='u_location_end',
        ),
        migrations.RemoveField(
            model_name='historicalnetworkdevice',
            name='u_location_start',
        ),
        migrations.RemoveField(
            model_name='historicalnetworkdevice',
            name='uptime',
        ),
        migrations.RemoveField(
            model_name='historicalnetworkdevice',
            name='zone',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='attribute',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='expire',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='framework',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='idc_model',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='rack',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='role',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='u_location_end',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='u_location_start',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='uptime',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='zone',
        ),
    ]
