# Generated by Django 3.2.19 on 2023-12-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_alter_idc_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkdevice',
            name='account',
            field=models.ManyToManyField(blank=True, null=True, to='asset.AssetAccount', verbose_name='管理账户'),
        ),
    ]
