# Generated by Django 3.2.19 on 2023-12-08 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0012_alter_networkdevice_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalnetworkdevice',
            name='memo',
            field=models.TextField(blank=True, default='', null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='memo',
            field=models.TextField(blank=True, default='', null=True, verbose_name='备注'),
        ),
    ]
