# Generated by Django 3.2.19 on 2023-10-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('int_utilization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interfaceused',
            name='host_type',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='设备类型'),
        ),
    ]
