# Generated by Django 3.2.19 on 2024-01-19 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionplan',
            name='vendor',
            field=models.CharField(default='H3C', max_length=50, verbose_name='厂商'),
        ),
    ]
