# Generated by Django 3.2.19 on 2023-06-27 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionplan',
            name='vendor',
            field=models.CharField(choices=[('H3C', 'H3C'), ('Huawei', 'Huawei'), ('Cisco', 'Cisco'), ('Ruijie', 'ruijie')], default='H3C', max_length=50, verbose_name='厂商'),
        ),
    ]
