# Generated by Django 3.2.19 on 2023-07-11 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_auto_20230710_1729'),
        ('automation', '0002_alter_collectionplan_vendor'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('operation', models.CharField(default='', max_length=50, verbose_name='运算符')),
                ('module', models.CharField(choices=[('BASE', '基础平台'), ('SouthDriver', '南向驱动')], default='BASE', max_length=50, verbose_name='执行模块')),
                ('method', models.CharField(choices=[('NETCONF', 'NETCONF'), ('CLI', 'CLI'), ('REST_API', 'REST_API')], default='CLI', max_length=50, verbose_name='执行方法')),
                ('execute', models.TextField(blank=True, default='', verbose_name='执行内容')),
                ('plugin', models.CharField(default='', max_length=50, verbose_name='解析插件标识')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='asset.vendor', verbose_name='厂商')),
            ],
            options={
                'verbose_name': '采集规则表',
                'verbose_name_plural': '采集规则表',
                'db_table': 'collection_rule',
            },
        ),
        migrations.CreateModel(
            name='CollectionMatchRule',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10, verbose_name='规则名')),
                ('pattern', models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='匹配字段')),
                ('regex', models.TextField(blank=True, default='', null=True, verbose_name='正则表达式')),
                ('rule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match_rule', to='automation.collectionrule')),
            ],
            options={
                'verbose_name': '采集规则匹配方法表',
                'verbose_name_plural': '采集规则匹配方法表',
                'db_table': 'collection_match_rule',
                'unique_together': {('rule', 'name')},
            },
        ),
    ]
