# Generated by Django 3.2.23 on 2024-08-04 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_alter_collectionplan_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autovars',
            name='ans_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='主机名'),
        ),
        migrations.AlterField(
            model_name='autovars',
            name='ans_obj',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='对象名'),
        ),
    ]
