# Generated by Django 3.2.19 on 2023-07-12 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_collectionmatchrule_collectionrule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionmatchrule',
            old_name='pattern',
            new_name='fields',
        ),
        migrations.RemoveField(
            model_name='collectionmatchrule',
            name='regex',
        ),
        migrations.AddField(
            model_name='collectionmatchrule',
            name='operator',
            field=models.CharField(blank=True, choices=[('__exact', '精确匹配'), ('__iexact', '不区分大小写的精确匹配'), ('__contains', '包含指定值'), ('__icontains', '不区分大小写包含指定值'), ('__startswith', '以指定值开头'), ('__endswith', '以指定值结尾'), ('__istartswith', '不区分大小写以指定值开头'), ('__iendswith', '不区分大小写以指定值结尾')], default='__exact', max_length=50, null=True, verbose_name='操作符'),
        ),
    ]
