# Generated by Django 3.2.23 on 2024-12-25 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_auto_20240805_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoevent',
            name='task',
            field=models.CharField(choices=[('DNAT', 'DNAT'), ('SNAT', 'SNAT'), ('安全策略', '安全策略'), ('QOS', 'QOS'), ('SLB负载均衡', 'SLB负载均衡'), ('一键封堵', '一键封堵'), ('地址对象', '地址对象'), ('服务对象', '服务对象'), ('一键切换', '一键切换')], default='', max_length=128, verbose_name='任务模块'),
        ),
        migrations.AlterField(
            model_name='autoflow',
            name='commit_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
        migrations.AlterField(
            model_name='autoflow',
            name='task',
            field=models.CharField(choices=[('DNAT', 'DNAT'), ('SNAT', 'SNAT'), ('安全策略', '安全策略'), ('QOS', 'QOS'), ('SLB负载均衡', 'SLB负载均衡'), ('一键封堵', '一键封堵'), ('地址对象', '地址对象'), ('服务对象', '服务对象'), ('一键切换', '一键切换')], default='', max_length=128, verbose_name='任务模块'),
        ),
    ]
