# Generated by Django 3.2.19 on 2023-07-12 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_auto_20230712_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='collectionmatchrule',
            name='value',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='匹配值'),
        ),
    ]
