# Generated by Django 3.2.23 on 2024-12-25 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_auto_20241225_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoflow',
            name='commit_time',
            field=models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='更新时间'),
        ),
    ]
