# Generated by Django 3.2.23 on 2026-03-19 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0005_alter_autoflow_commit_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoevent',
            name='task',
            field=models.CharField(choices=[('DNAT', 'DNAT'), ('SNAT', 'SNAT'), ('安全策略', '安全策略'), ('QOS', 'QOS'), ('SLB负载均衡', 'SLB负载均衡'), ('一键封堵', '一键封堵'), ('地址对象', '地址对象'), ('服务对象', '服务对象'), ('一键切换', '一键切换'), ('巡检', '巡检')], default='', max_length=128, verbose_name='任务模块'),
        ),
        migrations.AlterField(
            model_name='autoflow',
            name='task',
            field=models.CharField(choices=[('DNAT', 'DNAT'), ('SNAT', 'SNAT'), ('安全策略', '安全策略'), ('QOS', 'QOS'), ('SLB负载均衡', 'SLB负载均衡'), ('一键封堵', '一键封堵'), ('地址对象', '地址对象'), ('服务对象', '服务对象'), ('一键切换', '一键切换'), ('巡检', '巡检')], default='', max_length=128, verbose_name='任务模块'),
        ),
        migrations.AlterField(
            model_name='automationinventory',
            name='task',
            field=models.CharField(choices=[('一键封堵', '一键封堵'), ('网络打通', '网络打通'), ('巡检', '巡检')], default='一键封堵', max_length=64, verbose_name='任务模块'),
        ),
    ]
