# Generated by Django 3.2.19 on 2023-07-18 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0006_alter_collectionrule_operation'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='collectionmatchrule',
            index=models.Index(fields=['id'], name='collection__id_fde923_idx'),
        ),
        migrations.AddIndex(
            model_name='collectionrule',
            index=models.Index(fields=['id'], name='collection__id_1337f6_idx'),
        ),
    ]
