# Generated by Django 3.2.19 on 2023-07-18 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0007_auto_20230718_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectionrule',
            name='vendor',
        ),
        migrations.AddField(
            model_name='collectionrule',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='规则名'),
        ),
    ]
