# Generated by Django 3.2.19 on 2023-11-13 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0008_auto_20230718_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_user', models.CharField(default='', max_length=42, verbose_name='申请用户')),
                ('remote_ip', models.CharField(blank=True, max_length=128, null=True, verbose_name='调用IP')),
                ('task', models.CharField(choices=[('DNAT', 'DNAT'), ('SNAT', 'SNAT'), ('安全策略', '安全策略'), ('QOS', 'QOS'), ('SLB负载均衡', 'SLB负载均衡'), ('一键封堵', '一键封堵'), ('地址对象', '地址对象'), ('服务对象', '服务对象')], default='', max_length=128, verbose_name='任务模块')),
                ('commit_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
        ),
        migrations.CreateModel(
            name='AutoVars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_name', models.CharField(blank=True, max_length=32, null=True, verbose_name='主机名')),
                ('ans_host', models.GenericIPAddressField(blank=True, null=True, verbose_name='主机IP')),
                ('ans_vars', models.TextField(blank=True, null=True, verbose_name='主机变量')),
                ('ans_obj', models.CharField(blank=True, max_length=32, null=True, verbose_name='对象名')),
                ('ans_memo', models.CharField(blank=True, max_length=128, null=True, verbose_name='描述')),
                ('task', models.CharField(choices=[('DNAT', 'DNAT'), ('SNAT', 'SNAT'), ('安全策略', '安全策略'), ('QOS', 'QOS'), ('SLB负载均衡', 'SLB负载均衡'), ('地址对象', '地址对象'), ('服务对象', '服务对象')], default='地址对象', max_length=64, verbose_name='模块')),
            ],
        ),
        migrations.CreateModel(
            name='AutomationInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ans_group_name', models.CharField(max_length=32, unique=True, verbose_name='任务名称')),
                ('ans_group_vars', models.TextField(blank=True, null=True, verbose_name='组变量')),
                ('ans_group_memo', models.TextField(blank=True, null=True, verbose_name='组描述')),
                ('ans_group_datetime', models.DateTimeField(auto_now_add=True, verbose_name='添加时间')),
                ('task', models.CharField(choices=[('一键封堵', '一键封堵'), ('网络打通', '网络打通')], default='一键封堵', max_length=64, verbose_name='任务模块')),
                ('ans_group_hosts', models.ManyToManyField(related_name='to_inventory', to='automation.AutoVars', verbose_name='组内主机')),
            ],
        ),
        migrations.CreateModel(
            name='AutoFlow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_id', models.CharField(default='', max_length=128, verbose_name='任务ID')),
                ('origin', models.CharField(default='运维平台', max_length=128, verbose_name='来源')),
                ('task_result', models.TextField(default=None, editable=False, null=True, verbose_name='任务结果')),
                ('order_code', models.CharField(blank=True, max_length=128, null=True, verbose_name='工单')),
                ('device', models.GenericIPAddressField(blank=True, null=True, verbose_name='设备IP')),
                ('device_id', models.IntegerField(blank=True, null=True, verbose_name='设备ID')),
                ('commit_user', models.CharField(default='', max_length=42, verbose_name='申请用户')),
                ('commit_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task', models.CharField(choices=[('DNAT', 'DNAT'), ('SNAT', 'SNAT'), ('安全策略', '安全策略'), ('QOS', 'QOS'), ('SLB负载均衡', 'SLB负载均衡'), ('一键封堵', '一键封堵'), ('地址对象', '地址对象'), ('服务对象', '服务对象')], default='', max_length=128, verbose_name='任务模块')),
                ('method', models.CharField(choices=[('NETCONF', 'NETCONF'), ('SSH', 'SSH'), ('RESTAPI', 'RESTAPI')], default='', max_length=128, verbose_name='配置模式')),
                ('class_method', models.CharField(default='', max_length=128, verbose_name='类方法')),
                ('remote_ip', models.CharField(blank=True, max_length=128, null=True, verbose_name='调用IP')),
                ('kwargs', models.TextField(blank=True, default='{}', verbose_name='任务参数')),
                ('ttp', models.TextField(blank=True, default='{}', verbose_name='结果解析')),
                ('commands', models.TextField(blank=True, default='[]', verbose_name='下发命令')),
                ('back_off_commands', models.TextField(blank=True, default='[]', verbose_name='回退命令')),
                ('state', models.CharField(choices=[('Draft', 'Draft'), ('Approved', 'Approved'), ('Published', 'Published'), ('Failed', 'Failed'), ('BackOff', 'BackOff'), ('Finish', 'Finish')], default='Draft', max_length=200, verbose_name='流程状态')),
                ('code', models.IntegerField(blank=True, default=9000, null=True, verbose_name='状态码')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='automation.autoevent', verbose_name='关联事件')),
            ],
            options={
                'verbose_name': '自动化流程表',
                'verbose_name_plural': '自动化流程表',
                'db_table': 'auto_work_flow',
            },
        ),
    ]
