# Generated by Django 3.2.23 on 2024-12-19 13:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='设备名')),
                ('manage_ip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='管理地址')),
                ('last_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='备份时间')),
                ('idc_name', models.CharField(default='', max_length=100, null=True, verbose_name='机房')),
                ('model_name', models.CharField(default='', max_length=100, null=True, verbose_name='型号')),
                ('vendor', models.CharField(default='', max_length=100, null=True, verbose_name='厂商')),
                ('file_path', models.CharField(default='', max_length=200, null=True, verbose_name='文件路径')),
                ('commit', models.CharField(default='', max_length=200, null=True, verbose_name='提交commit')),
                ('git_type', models.CharField(choices=[('change', 'change'), ('add', 'add')], default='', max_length=200, null=True, verbose_name='类型')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '在线'), (1, '下线'), (2, '挂牌'), (3, '备用')], default=0, verbose_name='状态')),
                ('config_status', models.CharField(default='', max_length=100, verbose_name='备份状态')),
            ],
            options={
                'verbose_name': '配置备份表',
                'verbose_name_plural': '配置备份表',
                'db_table': 'config_backup',
            },
        ),
        migrations.CreateModel(
            name='ConfigCompliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(choices=[('H3C', 'H3C'), ('HUAWEI', 'HUAWEI'), ('Cisco_ios', 'Cisco_ios'), ('Ruijie', 'Ruijie'), ('Hillstone', 'Hillstone')], default='H3C', max_length=50, verbose_name='厂商')),
                ('pattern', models.CharField(choices=[('match-compliance', 'match-compliance'), ('mismatch-compliance', 'mismatch-compliance')], default='match-compliance', max_length=50, verbose_name='模式')),
                ('regex', models.TextField(default='', verbose_name='表达式')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='创建日期')),
            ],
            options={
                'verbose_name': '配置合规表',
                'verbose_name_plural': '配置合规表',
                'db_table': 'config_compliance',
            },
        ),
        migrations.CreateModel(
            name='ConfigComplianceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance', models.CharField(blank=True, max_length=100, null=True, verbose_name='结果')),
                ('manage_ip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='设备IP')),
                ('hostname', models.CharField(default='', max_length=200, verbose_name='设备名')),
                ('vendor', models.CharField(default='', max_length=100, verbose_name='厂商')),
                ('log_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='检查时间')),
                ('rule', models.CharField(default='', max_length=200, verbose_name='检查项')),
                ('rule_id', models.IntegerField(default=0, verbose_name='检查项id')),
            ],
            options={
                'verbose_name': '配置合规结果表',
                'verbose_name_plural': '配置合规结果表',
                'db_table': 'config_compliance_result',
            },
        ),
        migrations.CreateModel(
            name='ConfigComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='规则名')),
            ],
            options={
                'verbose_name': '配置合规规则表',
                'verbose_name_plural': '配置合规规则表',
                'db_table': 'config_compliance_rule',
            },
        ),
        migrations.CreateModel(
            name='ConfigTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(choices=[('H3C', 'H3C'), ('HUAWEI', 'HUAWEI'), ('Cisco_ios', 'Cisco_ios'), ('Ruijie', 'Ruijie'), ('Hillstone', 'Hillstone')], default='H3C', max_length=100, verbose_name='厂商')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='配置项名称')),
                ('config_yaml', models.TextField(blank=True, default='', verbose_name='yaml内容')),
                ('config_jinja2', models.TextField(blank=True, default='', verbose_name='jinja2内容')),
                ('config_text', models.TextField(blank=True, default='', verbose_name='配置命令')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '配置片段表',
                'verbose_name_plural': '配置片段表',
                'db_table': 'config_template',
            },
        ),
        migrations.CreateModel(
            name='TTPTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(choices=[('H3C', 'H3C'), ('HUAWEI', 'HUAWEI'), ('Cisco_ios', 'Cisco_ios'), ('Ruijie', 'Ruijie'), ('Hillstone', 'Hillstone')], default='H3C', max_length=100, verbose_name='厂商')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='名称')),
                ('ttp_content', models.TextField(blank=True, default='', verbose_name='模板内容')),
                ('datetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '配置片段表',
                'verbose_name_plural': '配置片段表',
                'db_table': 'ttp_template',
            },
        ),
        migrations.AddIndex(
            model_name='ttptemplate',
            index=models.Index(fields=['name', 'vendor'], name='ttp_templat_name_1944b9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ttptemplate',
            unique_together={('vendor', 'name')},
        ),
        migrations.AddIndex(
            model_name='configtemplate',
            index=models.Index(fields=['name', 'vendor'], name='config_temp_name_09cec8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='configtemplate',
            unique_together={('vendor', 'name')},
        ),
        migrations.AddField(
            model_name='configcompliancerule',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='config_center.configcompliancerule'),
        ),
        migrations.AddIndex(
            model_name='configcomplianceresult',
            index=models.Index(fields=['log_time'], name='config_comp_log_tim_df569d_idx'),
        ),
        migrations.AddIndex(
            model_name='configcomplianceresult',
            index=models.Index(fields=['manage_ip'], name='config_comp_manage__dbf185_idx'),
        ),
        migrations.AddField(
            model_name='configcompliance',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relate_compliance', to='config_center.configcompliancerule'),
        ),
        migrations.AddIndex(
            model_name='configbackup',
            index=models.Index(fields=['manage_ip', 'last_time'], name='config_back_manage__11749b_idx'),
        ),
        migrations.AddIndex(
            model_name='configcompliance',
            index=models.Index(fields=['vendor'], name='config_comp_vendor_292331_idx'),
        ),
        migrations.AddIndex(
            model_name='configcompliance',
            index=models.Index(fields=['datetime'], name='config_comp_datetim_5e0126_idx'),
        ),
    ]
