# Generated by Django 3.2.19 on 2024-07-09 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigBackup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=100, verbose_name='设备名')),
                ('manage_ip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='管理地址')),
                ('last_time', models.DateTimeField(auto_now=True, verbose_name='最近一次备份时间')),
                ('idc_name', models.CharField(default='', max_length=100, verbose_name='机房')),
                ('model_name', models.CharField(default='', max_length=100, verbose_name='型号')),
                ('vendor_name', models.CharField(default='', max_length=100, verbose_name='厂商')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '在线'), (1, '下线'), (2, '挂牌'), (3, '备用')], default=0, verbose_name='状态')),
                ('config_status', models.CharField(default='', max_length=100, verbose_name='备份状态')),
            ],
            options={
                'verbose_name': '配置备份表',
                'verbose_name_plural': '配置备份表',
                'db_table': 'config_backup',
            },
        ),
        migrations.AlterField(
            model_name='configcompliance',
            name='vendor',
            field=models.CharField(choices=[('H3C', 'H3C'), ('HUAWEI', 'HUAWEI'), ('Cisco_ios', 'Cisco_ios'), ('Ruijie', 'Ruijie'), ('Hillstone', 'Hillstone')], default='H3C', max_length=50, verbose_name='厂商'),
        ),
        migrations.AddIndex(
            model_name='configbackup',
            index=models.Index(fields=['manage_ip', 'last_time'], name='config_back_manage__11749b_idx'),
        ),
    ]
