# Generated by Django 3.2.19 on 2024-01-24 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configcompliance',
            name='vendor',
            field=models.CharField(choices=[('H3C', 'H3C'), ('HUAWEI', 'HUAWEI'), ('Cisco_ios', 'Cisco_ios'), ('Ruijie', 'Ruijie'), ('Hillstone', 'Hillstone')], default='H3C', max_length=50, verbose_name='厂商'),
        ),
    ]
