# Generated by Django 3.2.23 on 2025-04-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configbackup',
            name='detail',
            field=models.TextField(blank=True, null=True, verbose_name='详情'),
        ),
    ]
