# Generated by Django 3.2.23 on 2024-12-25 11:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configbackup',
            name='last_time',
            field=models.DateTimeField(default=django.utils.timezone.localtime, verbose_name='备份时间'),
        ),
    ]
