# Generated by Django 3.2.19 on 2024-07-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0002_auto_20240709_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configbackup',
            name='idc_name',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='机房'),
        ),
        migrations.AlterField(
            model_name='configbackup',
            name='model_name',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='型号'),
        ),
        migrations.AlterField(
            model_name='configbackup',
            name='vendor_name',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='厂商'),
        ),
    ]
