# Generated by Django 3.2.23 on 2025-03-11 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0003_alter_configbackup_git_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configbackup',
            name='commit',
        ),
        migrations.RemoveField(
            model_name='configbackup',
            name='git_type',
        ),
        migrations.AddField(
            model_name='configbackup',
            name='config_type',
            field=models.CharField(choices=[('startup', 'startup'), ('running', 'running')], default='running', max_length=100),
        ),
    ]
