# Generated by Codex on 2026-03-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("config_center", "0003_add_compliance_result_detail_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="configcompliance",
            name="intent",
            field=models.TextField(blank=True, default="", verbose_name="设计意图"),
        ),
    ]
