# Generated by Django 3.2.19 on 2024-07-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0003_auto_20240710_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='configbackup',
            name='commit',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='提交commit'),
        ),
        migrations.AddField(
            model_name='configbackup',
            name='file_path',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='文件路径'),
        ),
        migrations.AddField(
            model_name='configbackup',
            name='git_type',
            field=models.CharField(choices=[(0, '在线'), (1, '下线'), (2, '挂牌'), (3, '备用')], default='', max_length=200, null=True, verbose_name='类型'),
        ),
    ]
