# Generated by Django 3.2.19 on 2024-07-22 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0002_alter_configcompliance_vendor'),
        ('config_center', '0004_auto_20240710_1708'),
    ]

    operations = [
    ]
