# Generated by Django 3.2.23 on 2025-03-26 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0004_auto_20250311_1922'),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(blank=True, default='-', max_length=100, verbose_name='厂商')),
                ('startup_command', models.CharField(blank=True, default='', max_length=100, verbose_name='启动配置命令')),
                ('current_command', models.CharField(blank=True, default='', max_length=100, verbose_name='当前配置命令')),
            ],
            options={
                'verbose_name': '配置备份策略表',
                'verbose_name_plural': '配置备份策略表',
                'db_table': 'config_backup_policy',
            },
        ),
        migrations.AddIndex(
            model_name='backuppolicy',
            index=models.Index(fields=['vendor'], name='config_back_vendor_cb6dca_idx'),
        ),
    ]
