# Generated by Django 3.2.23 on 2024-07-22 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0005_merge_20240723_0217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configbackup',
            name='last_time',
            field=models.DateTimeField(auto_now=True, verbose_name='备份时间'),
        ),
    ]
