# Generated by Django 3.2.23 on 2025-03-28 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0005_auto_20250326_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuppolicy',
            name='remark',
            field=models.TextField(blank=True, default='-', verbose_name='备注'),
        ),
    ]
