# Generated by Django 3.2.23 on 2026-03-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0006_structureddriftpolicyaudit'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='structureddriftpolicy',
            name='structured__is_acti_3d559e_idx',
        ),
        migrations.RemoveIndex(
            model_name='structureddriftpolicy',
            name='structured__name_a23e5f_idx',
        ),
        migrations.RemoveIndex(
            model_name='structureddriftpolicyaudit',
            name='structured__action__1f25d0_idx',
        ),
        migrations.RemoveIndex(
            model_name='structureddriftpolicyaudit',
            name='structured__policy__043778_idx',
        ),
        migrations.AddIndex(
            model_name='structureddriftpolicy',
            index=models.Index(fields=['is_active'], name='structured__is_acti_a78f90_idx'),
        ),
        migrations.AddIndex(
            model_name='structureddriftpolicy',
            index=models.Index(fields=['name', 'updated_at'], name='structured__name_3763af_idx'),
        ),
        migrations.AddIndex(
            model_name='structureddriftpolicyaudit',
            index=models.Index(fields=['action', 'created_at'], name='structured__action_8a087a_idx'),
        ),
        migrations.AddIndex(
            model_name='structureddriftpolicyaudit',
            index=models.Index(fields=['policy', 'created_at'], name='structured__policy__5dca63_idx'),
        ),
    ]
