# Generated by Django 3.2.23 on 2025-03-28 03:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0006_backuppolicy_remark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configbackup',
            name='last_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='备份时间'),
        ),
    ]
