# Generated by Django 3.2.23 on 2024-10-08 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0006_alter_configbackup_last_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigComplianceResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compliance', models.CharField(blank=True, max_length=100, null=True, verbose_name='结果')),
                ('manage_ip', models.GenericIPAddressField(default='0.0.0.0', verbose_name='设备IP')),
                ('hostname', models.CharField(default='', max_length=200, verbose_name='设备名')),
                ('vendor', models.CharField(default='', max_length=100, verbose_name='厂商')),
                ('log_time', models.DateTimeField(auto_now=True, verbose_name='检查时间')),
                ('rule', models.CharField(default='', max_length=200, verbose_name='规则名')),
                ('regex', models.TextField(default='', max_length=200, verbose_name='正则表达式')),
            ],
            options={
                'verbose_name': '配置合规结果表',
                'verbose_name_plural': '配置合规结果表',
                'db_table': 'config_compliance_result',
            },
        ),
        migrations.AlterField(
            model_name='configcompliance',
            name='repair_cmds',
            field=models.TextField(blank=True, default='', null=True, verbose_name='修复命令'),
        ),
        migrations.AddIndex(
            model_name='configcomplianceresult',
            index=models.Index(fields=['log_time'], name='config_comp_log_tim_df569d_idx'),
        ),
        migrations.AddIndex(
            model_name='configcomplianceresult',
            index=models.Index(fields=['manage_ip'], name='config_comp_manage__dbf185_idx'),
        ),
    ]
