# Generated by Django 3.2.23 on 2024-09-25 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0008_auto_20240925_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configcomplianceresult',
            name='compliance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='结果'),
        ),
    ]
