# Generated by Django 3.2.23 on 2024-10-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0009_alter_configcomplianceresult_compliance'),
    ]

    operations = [
        migrations.AddField(
            model_name='configcomplianceresult',
            name='rule_id',
            field=models.IntegerField(default=0, verbose_name='规则id'),
        ),
        migrations.AlterField(
            model_name='configcomplianceresult',
            name='log_time',
            field=models.DateTimeField(verbose_name='检查时间'),
        ),
    ]
