# Generated by Django 3.2.23 on 2024-10-12 08:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0011_alter_configcomplianceresult_log_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configcomplianceresult',
            name='log_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='检查时间'),
        ),
    ]
