# Generated by Django 3.2.23 on 2024-10-14 02:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0012_alter_configcomplianceresult_log_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configbackup',
            name='last_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='备份时间'),
        ),
    ]
