# Generated by Django 3.2.23 on 2024-10-14 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0013_alter_configbackup_last_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configbackup',
            name='git_type',
            field=models.CharField(choices=[('change', 'change'), ('add', 'add')], default='', max_length=200, null=True, verbose_name='类型'),
        ),
    ]
