# Generated by Django 3.2.23 on 2024-10-22 03:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0014_alter_configbackup_git_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigComplianceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='规则名')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='config_center.configcompliancerule')),
            ],
            options={
                'verbose_name': '配置合规规则表',
                'verbose_name_plural': '配置合规规则表',
                'db_table': 'config_compliance_rule',
            },
        ),
        migrations.AddField(
            model_name='configcompliance',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='config_center.configcompliancerule'),
        ),
    ]
