# Generated by Django 3.2.23 on 2024-10-30 10:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0015_auto_20241022_1120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configcompliance',
            name='rule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='relate_compliance', to='config_center.configcompliancerule'),
        ),
    ]
