# Generated by Django 3.2.23 on 2024-10-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0016_alter_configcompliance_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='configbackup',
            name='vendor_alias',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='厂商'),
        ),
    ]
