# Generated by Django 3.2.23 on 2024-10-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0017_configbackup_vendor_alias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configbackup',
            old_name='vendor_alias',
            new_name='vendor',
        ),
        migrations.RemoveField(
            model_name='configbackup',
            name='vendor_name',
        ),
        migrations.AlterField(
            model_name='configcomplianceresult',
            name='rule',
            field=models.CharField(default='', max_length=200, verbose_name='检查项'),
        ),
        migrations.AlterField(
            model_name='configcomplianceresult',
            name='rule_id',
            field=models.IntegerField(default=0, verbose_name='检查项id'),
        ),
    ]
