# Generated by Django 3.2.23 on 2024-10-31 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0018_auto_20241031_0204'),
    ]

    operations = [
        migrations.AddField(
            model_name='configcomplianceresult',
            name='regex_result',
            field=models.TextField(default='', verbose_name='正则表达式'),
        ),
        migrations.AlterField(
            model_name='configcomplianceresult',
            name='regex',
            field=models.TextField(default='', verbose_name='正则表达式'),
        ),
    ]
