# Generated by Django 3.2.23 on 2024-10-31 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0019_auto_20241031_0937'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configcomplianceresult',
            name='regex',
        ),
        migrations.RemoveField(
            model_name='configcomplianceresult',
            name='regex_result',
        ),
    ]
