# Generated by Django 3.2.23 on 2024-10-31 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0020_auto_20241031_0942'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='configcompliance',
            name='config_comp_categor_4829f4_idx',
        ),
        migrations.RemoveField(
            model_name='configcompliance',
            name='category',
        ),
        migrations.RemoveField(
            model_name='configcompliance',
            name='is_repair',
        ),
        migrations.RemoveField(
            model_name='configcompliance',
            name='name',
        ),
        migrations.RemoveField(
            model_name='configcompliance',
            name='repair_cmds',
        ),
    ]
