# Generated by Django 3.2.23 on 2024-11-20 02:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('config_center', '0007_auto_20241008_1123'),
        ('config_center', '0021_auto_20241031_1039'),
    ]

    operations = [
    ]
