# Generated by Django 3.2.23 on 2026-03-02 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_id', models.IntegerField(verbose_name='封堵组ID')),
                ('ip_mask', models.JSONField(default=list, verbose_name='封堵IP列表')),
                ('range_start', models.CharField(blank=True, default='', max_length=64, verbose_name='范围起始IP')),
                ('range_end', models.CharField(blank=True, default='', max_length=64, verbose_name='范围结束IP')),
                ('action', models.CharField(choices=[('add', '封堵（添加）'), ('remove', '解封（删除）')], max_length=10, verbose_name='操作类型')),
                ('operator', models.CharField(max_length=64, verbose_name='操作人')),
                ('remote_ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='操作来源IP')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('success', '成功'), ('failed', '失败')], default='pending', max_length=10, verbose_name='状态')),
                ('auto_event_id', models.IntegerField(blank=True, null=True, verbose_name='关联自动化事件ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '封堵记录',
                'verbose_name_plural': '封堵记录',
                'db_table': 'dcs_block_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DnatRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=20, verbose_name='厂商')),
                ('device_ip', models.GenericIPAddressField(unpack_ipv4=True, verbose_name='设备管理IP')),
                ('rule_name', models.CharField(max_length=128, verbose_name='规则名称')),
                ('public_ip', models.CharField(max_length=64, verbose_name='公网IP')),
                ('private_ip', models.CharField(max_length=64, verbose_name='内网IP')),
                ('service', models.CharField(max_length=64, verbose_name='服务对象')),
                ('port', models.IntegerField(blank=True, null=True, verbose_name='端口')),
                ('operator', models.CharField(max_length=64, verbose_name='操作人')),
                ('status', models.CharField(choices=[('active', '生效'), ('removed', '已撤销'), ('failed', '发布失败')], default='active', max_length=10, verbose_name='状态')),
                ('raw_params', models.JSONField(default=dict, verbose_name='原始请求参数')),
                ('auto_flow_id', models.IntegerField(blank=True, null=True, verbose_name='关联流程记录ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': 'DNAT 发布记录',
                'verbose_name_plural': 'DNAT 发布记录',
                'db_table': 'dcs_dnat_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='dnatrecord',
            index=models.Index(fields=['device_ip', 'status'], name='idx_dnat_device_status'),
        ),
        migrations.AddIndex(
            model_name='dnatrecord',
            index=models.Index(fields=['public_ip'], name='idx_dnat_public_ip'),
        ),
        migrations.AddIndex(
            model_name='dnatrecord',
            index=models.Index(fields=['operator', 'created_at'], name='idx_dnat_operator_time'),
        ),
        migrations.AddIndex(
            model_name='blockrecord',
            index=models.Index(fields=['operator', 'created_at'], name='idx_block_operator_time'),
        ),
        migrations.AddIndex(
            model_name='blockrecord',
            index=models.Index(fields=['status'], name='idx_block_status'),
        ),
        migrations.AddIndex(
            model_name='blockrecord',
            index=models.Index(fields=['inventory_id'], name='idx_block_inventory'),
        ),
    ]
