# git用户配置
user:
  # 账号
  username:
  # 密码
  password:
# 项目信息配置
project:
  - pathname: base-platform
    url: https://gitee.com/NetAxeClub/base-platform-fronted.git
    branch: master
    username:
    password:
    # 是否初始化前端项目初始化文件
    #uninit: false
    port: 32200
    # 前端代理配置相关配置
    proxy: # 代理
      /base_platform: # 需代理的前缀
        target:
      /rbac:
        target:
    env: production
    envConfig:
      development:
        VITE_LOCAL_ROUTER: true
        VITE_BASIC_URL:
        VITE_RBAC_URL:
      production:
        VITE_LOCAL_ROUTER: false
        VITE_BASIC_URL:
        VITE_RBAC_URL:
  - pathname: cmdb
    url: https://gitee.com/NetAxeClub/cmdb-fronted.git
    branch: master
    username:
    password:
    # 是否初始化前端项目初始化文件
    #uninit: false
    port: 32200
    # 前端代理配置相关配置
    proxy: # 代理
      /base_platform: # 需代理的前缀
        target:
      /rbac:
        target:
      /api:
        target:
    env: production
    envConfig:
      development:
        VITE_LOCAL_ROUTER: true
        VITE_BASIC_URL:
        VITE_RBAC_URL:
      production:
        VITE_LOCAL_ROUTER: false
        VITE_BASIC_URL:
        VITE_RBAC_URL:

  - pathname: msggateway
    url: https://gitee.com/NetAxeClub/msggateway-fronted.git
    branch: master
    username:
    password:
    # 是否初始化前端项目初始化文件
    #uninit: false
    port: 32201
    # 前端代理配置相关配置
    proxy: # 代理
      /msg_gateway: # 需代理的前缀
        target: http://127.0.0.1:31101/
      /rbac:
        target: http://127.0.0.1:31101/
    env: production
    envConfig:
      development:
        VITE_LOCAL_ROUTER: true
        VITE_BASIC_URL:
        VITE_RBAC_URL:
      production:
        VITE_LOCAL_ROUTER: true
        VITE_BASIC_URL:
        VITE_RBAC_URL:

  - pathname: ipam
    url: https://gitee.com/NetAxeClub/ipam-fronted.git
    branch: master
    username:
    password:
    # 是否初始化前端项目初始化文件
    #uninit: false
    port: 32203
    # 前端代理配置相关配置
    proxy: # 代理
      /msg_gateway: # 需代理的前缀
        target: http://127.0.0.1:31101/
      /rbac:
        target: http://127.0.0.1:31101/
    env: production
    envConfig:
      development:
        VITE_LOCAL_ROUTER: true
        VITE_BASIC_URL:
        VITE_RBAC_URL:
      production:
        VITE_LOCAL_ROUTER: true
        VITE_BASIC_URL:
        VITE_RBAC_URL:
